crud_login_app/apps/crud/models.py
from datetime import datetime

from flask_login import UserMixin
from apps.app import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True, unique=True)
    email = db.Column(db.String, index=True, unique=True)
    # login = db.Column(db.Boolean(1), index=True, default=False)
    password_hash = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    updated_at = db.Column(db.DateTime, nullable=True, default=datetime.now, onupdate=datetime.now)

    def __repr__(self) -> str:
        return f'<User {self.id}>'

    @property
    def password(self) -> None:
        raise AttributeError('Password is not a readable attribute')

    @password.setter
    def password(self, password: str) -> None:
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)

    def is_duplicate(self, username: str, email: str) -> bool:
        return User.query.filter(
            (User.username == username) | (User.email == email)
        ).first() is not None

@login_manager.user_loader
def load_user(user_id: int) -> User:
    return User.query.get(int(user_id))

crud_login_app/apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, length

class UserForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[
            DataRequired(message='Username is required'),
            length(min=4, max=20, message='Username must be between 4 and 20 characters')
        ]
    )
    email = StringField(
        'Email',
        validators=[
            DataRequired(message='Email is required'),
            Email(message='Invalid email'),
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired(message='Password is required'),
            length(min=4, max=20, message='Password must be between 4 and 20 characters')
        ]
    )
    submit = SubmitField('Submit')

crud_login_app/apps/crud/__init__.py
import apps.crud.models

crud_login_app/apps/crud/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm
from flask_login import login_required

crud = Blueprint(
    'crud',
    __name__,
    template_folder='templates',
    static_folder='static'
)

@crud.route('/')
def index() -> render_template:
    return render_template('crud/index.html')

@crud.route('/sql')
def sql() -> render_template:
    db.session.query(User).all()
    return 'Check the console'
    # return redirect(url_for('crud.index'))

@login_required
@crud.route('/users')
def users() -> render_template:
    users = User.query.all()
    return render_template('crud/users.html', users=users)

@login_required
@crud.route('/users/new', methods=['GET', 'POST'])
def create_user() -> render_template:
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data
        )

        db.session.add(user)
        db.session.commit()

        flash('User created successfully', 'success')

        return redirect(url_for('crud.users'))
    return render_template('crud/create.html', form=form)

@login_required
@crud.route('/users/<int:user_id>', methods=['GET', 'POST'])
def edit_user(user_id: int) -> render_template:
    form = UserForm()
    user = User.query.filter_by(id=user_id).first()
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data

        db.session.add(user)
        db.session.commit()

        flash('User updated successfully', 'success')

        return redirect(url_for('crud.users'))
    return render_template('crud/edit.html', user=user, form=form)

@login_required
@crud.route('/users/<int:user_id>/delete', methods=['POST'])
def delete_user(user_id: int) -> render_template:
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()

    flash('User deleted successfully', 'success')

    return redirect(url_for('crud.users'))

crud_login_app/apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{{url_for('crud.static', filename='style.css')}}" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <h1 class="crud">CRUDアプリケーション</h1>
        {% block content %}{% endblock %}
    </body>
</html>

crud_login_app/apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}Create User{% endblock %}
{% block content %}
        <h2>ユーザー新規作成</h2>
        <form action="{{url_for('crud.create_user')}}" method="POST" novalidate="novalidate">
            {{form.csrf_token}}
            <p>
                {{form.username.label}} {{form.username(placeholder="ユーザー名")}}
            </p>
                {% for error in form.username.errors %}
                    <span class="error">{{error}}</span>
                {% endfor %}
            <p>
                {{form.email.label}} {{form.email(placeholder="メールアドレス")}}
            </p>
                {% for error in form.email.errors %}
                    <span class="error">{{error}}</span>
                {% endfor %}
            <p>
                {{form.password.label}} {{form.password(placeholder="パスワード")}}
            </p>
                {% for error in form.password.errors %}
                    <span class="error">{{error}}</span>
                {% endfor %}
            <p>{{form.submit()}}</p>
        </form>
        <button><a href="{{url_for('crud.users')}}">Back</a></button>
{% endblock %}

crud_login_app/apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}CRUDアプリケーション{% endblock %}
{% block content %}
        <h2>ユーザー編集</h2>
        <form action="{{url_for('crud.edit_user', user_id=user.id)}}" method="POST" novalidate="novalidate">
            {{form.csrf_token}}
            <p>
                {{form.username.label}} {{form.username(placeholder="ユーザー名", value=user.username)}}
            </p>
                {% for error in form.username.errors %}
                    <span class="error">{{error}}</span>
                {% endfor %}
            <p>
                {{form.email.label}} {{form.email(placeholder="メールアドレス", value=user.email)}}
            </p>
                {% for error in form.email.errors %}
                    <span class="error">{{error}}</span>
                {% endfor %}
            <p>
                {{form.password.label}} {{form.password(placeholder="パスワード")}}
            </p>
                {% for error in form.password.errors %}
                    <span class="error">{{error}}</span>
                {% endfor %}
                <p><input type="submit" value="Update"></p>
            </form>

            <form action="{{url_for('crud.delete_user', user_id=user.id)}}" method="POST" novalidate="novalidate">
                {{form.csrf_token}}
                <p><input type="submit" value="Delete"></p>
            </form>
            <button><a href="{{url_for('crud.users')}}">Back</a></button>
{% endblock %}

crud_login_app/apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}

crud_login_app/apps/crud/templates/crud/users.html
{% extends 'crud/base.html' %}
{% block title %}ユーザー一覧{% endblock %}
{% block content %}
        <h2>ユーザー一覧</h2>
        <a href="{{url_for('crud.create_user')}}">新規作成</a>

        <table>
            <tr>
                <!-- <th>ユーザーID</th> -->
                <th>ユーザー名</th>
                <th>メールアドレス</th>
                <th></th>
            </tr>
            {% for user in users %}
            <tr>
                <!-- <td>{{user.id}}</td> -->
                <td>{{user.username}}</td>
                <td>{{user.email}}</td>
                <td><a href="{{url_for('crud.edit_user', user_id=user.id)}}">編集</a></td>
            </tr>
            {% endfor %}
        </table>
{% endblock %}